DROP TABLE IF EXISTS PRICES;
DROP TABLE IF EXISTS BRANDS;

CREATE TABLE BRANDS
(
    ID   BIGINT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL
);

CREATE TABLE PRICES
(
    BRAND_ID   BIGINT         NOT NULL,
    PRODUCT_ID BIGINT         NOT NULL,
    PRICE_LIST INT            NOT NULL,
    START_DATE TIMESTAMP      NOT NULL,
    END_DATE   TIMESTAMP      NOT NULL,
    PRIORITY   INT            NOT NULL,
    PRICE      DECIMAL(10, 2) NOT NULL,
    CURR       VARCHAR(3)     NOT NULL,
    PRIMARY KEY (BRAND_ID, PRODUCT_ID, PRICE_LIST),
    CONSTRAINT FK_PRICES_BRAND
        FOREIGN KEY (BRAND_ID)
        REFERENCES BRANDS(ID)
);

CREATE INDEX IDX_PRICES_LOOKUP
    ON PRICES (
               BRAND_ID,
               PRODUCT_ID,
               START_DATE,
               END_DATE,
               PRIORITY DESC
        );